name: predictor
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.3.4
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  retrofit: ^4.0.1
  injectable: ^2.1.2
  logger: ^1.3.0
  get_it: ^7.6.0
  dio: ^5.1.2
  freezed_annotation: ^2.2.0
  percent_indicator: ^4.2.3
  country_codes: ^2.2.0
  json_serializable: ^6.6.2
  dio_cache_interceptor: ^3.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19
  build_runner: ^2.3.3
  retrofit_generator: ^7.0.1
  json_annotation: ^4.8.1
  injectable_generator: ^2.1.6
  test: ^1.22.0


flutter:
  uses-material-design: true
  assets:
    - assets/
